#pragma config(Sensor, in1,    lightsensor,    sensorReflection)
#pragma config(Sensor, in2,    line,           sensorLineFollower)
#pragma config(Sensor, in3,    poten,          sensorPotentiometer)
#pragma config(Sensor, dgtl1,  touch,          sensorTouch)
#pragma config(Sensor, dgtl2,  input,          sensorDigitalIn)
#pragma config(Sensor, dgtl3,  output,         sensorDigitalOut)
#pragma config(Sensor, dgtl4,  quad1,          sensorQuadEncoder)
#pragma config(Motor,  port2,           leftmotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           servo,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port4,           rightmotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (1==1){
  	while (SensorValue(touch) == 1){
			motor[leftmotor] =127;
			motor[rightmotor] =127;
			motor[flashlight] =127;
		}
		while(SensorValue(touch)==0){
			motor[leftmotor] =0;
			motor[rightmotor] =0;
			motor[flashlight] =0;
		}
	}


}
